---
- platform: group
  name: hallway lights
  entities:
    - light.hall1
- platform: group
  name: kitchen lights
  entities:
    - light.lightstripkitchen1
- platform: group
  name: livingroom lights
  entities:
    - light.livingroom1
- platform: group
  name: bedroom lights
  entities:
    - light.bedroom1
    - light.bedroom2
    - light.bedroom3



- platform: group
  name: candle lights
  entities:
    - light.bedroom2
    - light.bedroom3
    - light.livingroom1
