---
- platform: bayesian
  name: "in_bed"
  prior: 0.5
  probability_threshold: 0.85
  observations:
    - entity_id: "group.family"
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: "state"
      to_state: "home"
    - entity_id: "binary_sensor.hue_motion_sensor_hallway_motion"
      prob_given_true: 0.5
      prob_given_false: 0.4
      platform: "state"
      to_state: "off"
    - entity_id: "binary_sensor.cam01_motion"
      prob_given_true: 0.5
      prob_given_false: 0.4
      platform: "state"
      to_state: "off"
    - entity_id: "binary_sensor.hue_motion_sensor_kitchen_motion"
      prob_given_true: 0.4
      prob_given_false: 0.2
      platform: "state"
      to_state: "off"
    - entity_id: "sun.sun"
      prob_given_true: 0.8
      prob_given_false: 0.1
      platform: "state"
      to_state: "below_horizon"
    - entity_id: "group.all_lights"
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: "state"
      to_state: "off"
