---
- platform: ping
  hosts:
    benjamin_smartphone: smartphone.bds.home.arpa
    count: 2
  consider_home: 600

- platform: ping
  hosts:
    gf_smartphone: gf.bds.home.arpa
    count: 2
  consider_home: 600
