#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

DNSCRYPT_PROXY_PORT=5300
DNSCRYPT_PROXY_VERSION=1.9.4
DNSCRYPT_RESOLVERS='dnscrypt.org-fr cs-fr cs-fr2 cs-uk'

apt-get install -y \
  build-essential \
  dnsutils \
  libsodium-dev \
  libsystemd-dev \
  pkg-config

mkdir -p "$HOME/dnscrypt-proxy/${DNSCRYPT_PROXY_VERSION}"

pushd "$HOME/dnscrypt-proxy/${DNSCRYPT_PROXY_VERSION}"

if [[ ! -f "dnscrypt-proxy-${DNSCRYPT_PROXY_VERSION}.tar.gz" ]]; then
  wget \
    "https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-proxy-${DNSCRYPT_PROXY_VERSION}.tar.gz" \
    -O "dnscrypt-proxy-${DNSCRYPT_PROXY_VERSION}.tar.gz"
  tar -zxf "dnscrypt-proxy-${DNSCRYPT_PROXY_VERSION}.tar.gz" --strip-components=1 -C \
    "$HOME/dnscrypt-proxy/${DNSCRYPT_PROXY_VERSION}"
fi

if ! /usr/local/sbin/dnscrypt-proxy --version | grep -q "$DNSCRYPT_PROXY_VERSION"; then
  ldconfig
  ./configure --with-systemd
  make
  make install
fi

popd

for resolver in $DNSCRYPT_RESOLVERS; do
cat <<DNSCRYPTSOCKET > "/etc/systemd/system/dnscrypt-proxy@${resolver}.socket"
[Unit]
Description=dnscrypt-proxy listening socket

[Socket]
ListenStream=127.0.0.1:${DNSCRYPT_PROXY_PORT}
ListenDatagram=127.0.0.1:${DNSCRYPT_PROXY_PORT}

[Install]
WantedBy=sockets.target
DNSCRYPTSOCKET

  DNSCRYPT_PROXY_PORT=$((DNSCRYPT_PROXY_PORT + 1))
done

function _generate_install_section {
  install_section="[Install]\n"

  for resolver in $DNSCRYPT_RESOLVERS; do
    install_section+="Also=dnscrypt-proxy@${resolver}.socket\n"
  done

  install_section+="WantedBy=multi-user.target\n"

  echo -e "$install_section"
}

cat <<-DNSCRYPTPROXYCONF > /etc/systemd/system/dnscrypt-proxy@.service
[Unit]
Description=DNSCrypt client proxy
Documentation=man:dnscrypt-proxy(8)
Requires=dnscrypt-proxy@%i.socket
After=network.target
Before=nss-lookup.target

$(_generate_install_section)

[Service]
Type=simple
NonBlocking=true
ExecStart=/usr/local/sbin/dnscrypt-proxy --resolver-name=%i --user=nobody --ephemeral-keys
Restart=always
DNSCRYPTPROXYCONF

# ensure `nobody` home directory exist to avoid chroot errors
# shellcheck disable=SC2174
mkdir -m 0700 -p /nonexistent
chown nobody.nogroup /nonexistent

systemctl daemon-reload
systemctl enable dnscrypt-proxy@.service

for resolver in $DNSCRYPT_RESOLVERS; do
  service "dnscrypt-proxy@${resolver}" restart
done
