#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

apt-get install -y curl pwgen tor

cat <<TORCONF > /etc/tor/torrc
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
AvoidDiskWrites 1
ControlPort 9051
ClientOnly 1
DNSListenAddress 127.0.0.1
DNSPort 9053
HardwareAccel 1
HashedControlPassword $(tor --hash-password "$(pwgen 16)" | tail -n 1)
Log notice syslog
NumCPUs 2
SocksPort 9050
TORCONF

service tor reload || service tor restart

# check if Tor is Up & Running
tor-resolve bds.io >/dev/null
tor-resolve -x 8.8.8.8 >/dev/null

torify curl -s https://check.torproject.org/ | grep -q -m 1 'Congratulations'
curl \
  --socks5 localhost:9050 \
  --socks5-hostname localhost:9050 \
  -s https://check.torproject.org/ \
  | grep -q -m 1 'Congratulations'
