#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

apt-get install -y fail2ban

systemctl disable fail2ban
service fail2ban stop

# SSH jail
cat <<JAIL_SSH > /etc/fail2ban/jail.d/sshd.conf
[ssh-iptables]
enabled = true
filter = sshd
action = iptables[name=SSH, port=ssh, protocol=tcp]
logpath = /var/log/auth.log
maxretry = 2
JAIL_SSH

# Home Assistant jail
cat <<FILTER_HASS > /etc/fail2ban/filter.d/hass.local
[INCLUDES]
before = common.conf

[Definition]
failregex = ^%(__prefix_line)s.*Login attempt or request with invalid authentication from <HOST>.*$

ignoreregex =
FILTER_HASS

cat <<JAIL_HASS > /etc/fail2ban/jail.d/hass.conf
[hass-iptables]
enabled = true
filter = hass
action = iptables-allports[name=HASS]
logpath = /home/homeassistant/.homeassistant/home-assistant.log
maxretry = 5
JAIL_HASS

# Supervisord settings
cat <<SUPERVISOR_FAIL2BAN > /etc/supervisor/conf.d/fail2ban.conf
[program:fail2ban]
autorestart = true
command = /usr/bin/python3 /usr/bin/fail2ban-server -x -f -s /var/run/fail2ban/fail2ban.sock
group = root
redirect_stderr = true
stderr_logfile = syslog
stdout_logfile = syslog
user = root
SUPERVISOR_FAIL2BAN

supervisorctl reread
supervisorctl update
supervisorctl start fail2ban
