#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

# YOLO, Ok?
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait

mkdir -p /var/cache/netdata
chown -R netdata:netdata /var/cache/netdata

unlink /etc/cron.daily/netdata-updater

systemctl disable netdata
service netdata stop

cat <<NETDATA > /etc/netdata.conf
[global]
history = 1800
memory mode = ram
update every = 2
NETDATA

cat <<SUPERVISOR_DNSMASQ > /etc/supervisor/conf.d/netdata.conf
[program:netdata]
autorestart = true
command = /usr/sbin/netdata -P /run/netdata/netdata.pid -D -u netdata -i 0.0.0.0 -p 19999
group = root
redirect_stderr = true
stderr_logfile = syslog
stdout_logfile = syslog
user = root
SUPERVISOR_DNSMASQ

supervisorctl reread
supervisorctl update
supervisorctl start netdata
