#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

DNSCRYPT_PROXY_PORT=5300
DNSCRYPT_PROXY_VERSION=1.9.5
DNSCRYPT_RESOLVERS='cs-cfi dnscrypt.org-fr'

apt-get install -y \
  build-essential \
  dnsutils \
  libsodium-dev \
  libsystemd-dev \
  pkg-config

mkdir -p "$HOME/dnscrypt-proxy/${DNSCRYPT_PROXY_VERSION}"

pushd "$HOME/dnscrypt-proxy/${DNSCRYPT_PROXY_VERSION}"

if [[ ! -f "dnscrypt-proxy-${DNSCRYPT_PROXY_VERSION}.tar.gz" ]]; then
  wget \
    "https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-proxy-${DNSCRYPT_PROXY_VERSION}.tar.gz" \
    -O "dnscrypt-proxy-${DNSCRYPT_PROXY_VERSION}.tar.gz"
  tar -zxf "dnscrypt-proxy-${DNSCRYPT_PROXY_VERSION}.tar.gz" --strip-components=1 -C \
    "$HOME/dnscrypt-proxy/${DNSCRYPT_PROXY_VERSION}"
fi

if [[ ! -f /usr/local/sbin/dnscrypt-proxy ]] ||
  ! /usr/local/sbin/dnscrypt-proxy --version | grep -q "$DNSCRYPT_PROXY_VERSION"; then
  ldconfig
  ./configure --with-systemd
  make
  make install
fi

popd

SUPERVISOR_GROUP=''

for resolver in $DNSCRYPT_RESOLVERS; do
  program="dnscrypt-proxy-${resolver}"
cat <<SUPERVISOR_DNSCRYPT > "/etc/supervisor/conf.d/${program}.conf"
[program:$program]
autorestart = true
command = /usr/local/sbin/dnscrypt-proxy --local-address=127.0.0.1:$DNSCRYPT_PROXY_PORT --resolver-name=$resolver --user=nobody --ephemeral-keys
group = root
redirect_stderr = true
stderr_logfile = syslog
stdout_logfile = syslog
user = root
SUPERVISOR_DNSCRYPT

  DNSCRYPT_PROXY_PORT=$((DNSCRYPT_PROXY_PORT + 1))
  SUPERVISOR_GROUP="${program},${SUPERVISOR_GROUP}"
done

cat <<SUPERVISOR_DNSCRYPT_GROUP > '/etc/supervisor/conf.d/dnscrypt-proxy.conf'
[group:dnscrypt-proxy]
programs = ${SUPERVISOR_GROUP%,}
SUPERVISOR_DNSCRYPT_GROUP

# ensure `nobody` home directory exist to avoid chroot errors
# shellcheck disable=SC2174
mkdir -m 0700 -p /nonexistent
chown nobody.nogroup /nonexistent

systemctl daemon-reload
systemctl disable dnscrypt-proxy@.service
systemctl stop dnscrypt-proxy@\*

supervisorctl reread
supervisorctl update
supervisorctl start dnscrypt-proxy:*
