#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

apt-get install -y \
  dnsmasq \
  dnsutils \
  wget

mkdir -p '/etc/hosts.d'

cat <<DNSMASQCONF > /etc/dnsmasq.conf
# http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq.conf.example

addn-hosts=/etc/hosts.d
all-servers
bind-interfaces
bogus-priv
cache-size=10000
cname=bds.home,nestor.bds.home
dhcp-authoritative
dhcp-host=5c:aa:fd:5a:84:90,sonos,192.168.1.248
dhcp-host=00:17:88:19:7b:ab,hue,192.168.1.249
dhcp-host=00:11:32:64:d8:87,nas,192.168.1.250
dhcp-host=b8:27:eb:5d:d1:61,albert,192.168.1.251
dhcp-host=b8:27:eb:3f:d6:ec,nestor,192.168.1.252
dhcp-host=70:3a:cb:74:2e:75,wifi,192.168.1.253
dhcp-host=64:7c:34:31:28:68,router,192.168.1.254
dhcp-option=1,255.255.255.0
dhcp-option=3,192.168.1.254
dhcp-option=6,192.168.1.251
dhcp-range=192.168.1.10,192.168.1.20,24h
domain-needed
domain=bds.home,192.168.1.0/24
group=nogroup
host-record=sonos.bds.home,sonos,192.168.1.248
host-record=hue.bds.home,hue,192.168.1.249
host-record=nas.bds.home,nas,192.168.1.250
host-record=albert.bds.home,albert,192.168.1.251
host-record=nestor.bds.home,nestor,192.168.1.252
host-record=wifi.bds.home,wifi,192.168.1.253
host-record=router.bds.home,router,192.168.1.254
interface=eth0
local=/bds.home/
log-async=0
log-dhcp
log-facility=/dev/fd/2
no-negcache
no-resolv
port=53
proxy-dnssec
server=127.0.0.1#5300
server=127.0.0.1#5301
server=127.0.0.1#5302
server=127.0.0.1#5303
server=127.0.0.1#9053
stop-dns-rebind
strict-order
user=nobody
DNSMASQCONF

# Extending and consolidating hosts files, https://github.com/StevenBlack/hosts
rm -f '/etc/hosts.d/*'
wget 'https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts' \
  -O '/etc/hosts.d/fakenews-gambling'

systemctl disable dnsmasq
service stop dnsmasq || true

cat <<SUPERVISOR_DNSMASQ > /etc/supervisor/conf.d/dnsmasq.conf
[program:dnsmasq]
autorestart = true
command = /usr/sbin/dnsmasq -k -C /etc/dnsmasq.conf
group = root
redirect_stderr = true
stderr_logfile = syslog
stdout_logfile = syslog
user = root
SUPERVISOR_DNSMASQ

supervisorctl reread
supervisorctl update
supervisorctl start dnsmasq
