#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

ENABLE_TOR=${ENABLE_TOR:=1}

apt-get install -y polipo wget

cat <<POLIPO > /etc/polipo/config
allowedClients = 127.0.0.1, 192.168.1.0/24
allowedPorts = 1-65535
cacheIsShared = false
censorReferer = maybe
censoredHeaders = from,accept-language,x-pad,link
chunkHighMark = 67108864
disableIndexing = false
disableVia = true
diskCacheRoot = ""
dnsNameServer = 127.0.0.1
dnsUseGethostbyname = true
logSyslog = true
maxConnectionAge = 5m
maxConnectionRequests = 120
proxyAddress = "0.0.0.0"
proxyName = "pi.bds.home"
proxyPort = 8123
scrubLogs = true
tunnelAllowedPorts = 1-65535
POLIPO

cat <<ULIMIT > /etc/security/limits.d/proxy.conf
proxy - nofile 65536
ULIMIT

if [[ $ENABLE_TOR -eq 1 ]]; then
  cat <<POLIPO >> /etc/polipo/config
diskCacheRoot=""
socksParentProxy = "localhost:9050"
socksProxyType = socks5
POLIPO
fi

service polipo restart

if [[ $ENABLE_TOR -eq 1 ]]; then
  env https_proxy='http://127.0.0.1:8123' \
    wget -q -O - https://check.torproject.org/ \
    | grep 'Congratulations. This browser is configured to use Tor.'
else
  env https_proxy='http://127.0.0.1:8123' \
    wget -q -O - https://check.torproject.org/ \
    | grep 'Sorry. You are not using Tor.'
fi
