#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

[[ $(hostname -s) != 'nestor' ]] && exit 0

apt-get install -y \
  bluetooth \
  libbluetooth-dev \
  libboost-python-dev \
  libboost-thread-dev \
  libcap2-bin \
  libglib2.0-dev \
  net-tools \
  nmap \
  nut-client \
  pkg-config \
  postgresql-9.6 \
  postgresql-server-dev-9.6 \
  python-dev \
  python-psycopg2 \
  python3-dev \
  python3-pip \
  python3-venv


#
# Setup PG
#
cat <<PG_CONF_D > /etc/postgresql/9.6/main/conf.d/00-tuning.conf
archive_command = 'test ! -f /mnt/nas/archivedir/%f && cp %p /mnt/nas/archivedir/%f'
archive_mode = off
log_destination = 'stderr'
max_wal_senders = 3
unix_socket_directories = '/var/run/postgresql,/tmp'
wal_level = replica
PG_CONF_D

cat <<START_PG > /usr/local/bin/start-postgresql
#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

mkdir -p \
  /etc/postgresql/9.6/main/conf.d \
  /var/run/postgresql/9.6-main.pg_stat_tmp \
  /mnt/nas/archivedir

chmod -R 0700 \
  /etc/postgresql/9.6/main/conf.d \
  /var/run/postgresql/9.6-main.pg_stat_tmp \
  /mnt/nas/archivedir

chown -R postgres.postgres \
  /etc/postgresql/9.6/main/conf.d \
  /var/run/postgresql \
  /mnt/nas/archivedir

exec runuser -l postgres -c 'exec /usr/lib/postgresql/9.6/bin/postgres \
  -D /var/lib/postgresql/9.6/main \
  -c config_file=/etc/postgresql/9.6/main/postgresql.conf'
START_PG

chmod +x /usr/local/bin/start-postgresql

cat <<SUPERVISOR_PG > /etc/supervisor/conf.d/postgresql.conf
[program:postgresql]
autorestart = true
command = /usr/local/bin/start-postgresql
group = root
redirect_stderr = true
stderr_logfile = syslog
stdout_logfile = syslog
user = root
SUPERVISOR_PG

systemctl disable postgresql
service postgresql stop
supervisorctl reread
supervisorctl update
supervisorctl start postgresql

sudo -u postgres psql postgres -tAc \
  "SELECT 1 FROM pg_roles WHERE rolname='homeassistant'" | grep -q 1 \
  || sudo -u postgres createuser homeassistant

sudo -u postgres psql postgres -tAc \
  "SELECT 1 FROM pg_roles WHERE rolname='replication'" | grep -q 1 \
  || sudo -u postgres createuser replication -c 5 --replication

sudo -u postgres psql homeassistant -c '' 2>/dev/null \
  || sudo -u postgres createdb -O homeassistant homeassistant

#
# Setup Home Assistant
#
adduser --system homeassistant
getent group homeassistant || addgroup homeassistant
usermod -G dialout -a homeassistant

# http://unix.stackexchange.com/questions/96106/bluetooth-le-scan-as-non-root
setcap cap_net_raw,cap_net_admin+eip \
  "$(readlink -f /srv/homeassistant/bin/python3)"

# shellcheck disable=SC2174
mkdir -m 0700 -p /srv/homeassistant
chown -R homeassistant:homeassistant /srv/homeassistant

sudo -u homeassistant pip3 install --upgrade virtualenv
sudo -u homeassistant python3 -m venv /srv/homeassistant
sudo -u homeassistant \
  bash -c 'source /srv/homeassistant/bin/activate && pip3 install --upgrade homeassistant psycopg2'
cp files/home/homeassistant/.homeassistant/configuration.yaml \
  /home/homeassistant/.homeassistant/configuration.yaml
rsync -za files/home/homeassistant/.homeassistant/scenes/ \
  /home/homeassistant/.homeassistant/scenes/
chown -R homeassistant:homeassistant /srv/homeassistant

cat <<SUPERVISOR_HASS > /etc/supervisor/conf.d/hass.conf
[program:hass]
autorestart = true
command = /srv/homeassistant/bin/hass
group = homeassistant
redirect_stderr = true
stderr_logfile = syslog
stdout_logfile = syslog
user = homeassistant
SUPERVISOR_HASS

supervisorctl reread
supervisorctl update
supervisorctl start hass
