#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

crontab -u root "${DIR}/../files/var/spool/cron/crontabs/root"
