---
title: BDS Home
views:
  - title: Home
    path: home
    icon: mdi:home
    theme: modern-home
    badges:
      - entity: person.benjamin
      - entity: person.gf
      - entity: input_boolean.vacation_mode
      - entity: input_boolean.guest_mode
    cards:
      - type: entities
        title: Power & System Status
        entities:
          - sensor.ups_load
          - sensor.ups_battery_charge
          - sensor.ups_status
        icon: mdi:battery
        
      - type: grid
        columns: 2
        square: false
        cards:
          - type: light
            entity: light.livingroom_lights
            name: Living Room
            icon: mdi:sofa
            
          - type: light
            entity: light.kitchen_lights
            name: Kitchen
            icon: mdi:chef-hat
            
          - type: light
            entity: light.bedroom_lights
            name: Bedroom
            icon: mdi:bed
            
          - type: light
            entity: light.kid_bedroom_lights
            name: Kid Bedroom
            icon: mdi:teddy-bear
            
          - type: light
            entity: light.bathroom_lights
            name: Bathroom
            icon: mdi:shower
            
      - type: picture-entity
        entity: camera.cam01
        name: Security Camera
        show_state: false
        show_name: true
            
      - type: entities
        title: Quick Room Overview
        entities:
          - light.livingroom_lights
          - light.kitchen_lights
          - light.bedroom_lights
          - light.kid_bedroom_lights
          - light.bathroom_lights
              
  - title: Living Room
    path: livingroom
    icon: mdi:sofa
    theme: modern-home
    cards:
      - type: entities
        title: Living Room Lights
        entities:
          - light.livingroom1
          - light.livingroom2
          - light.livingroom4
          
      - type: media-control
        entity: media_player.living_room
        
      - type: entities
        title: Environment
        entities:
          - sensor.ups_input_voltage
          - sensor.ups_load
          
  - title: Kitchen
    path: kitchen
    icon: mdi:chef-hat
    theme: modern-home
    cards:
      - type: light
        entity: light.kitchen1
        name: Kitchen Light
        
      - type: entities
        title: Kitchen Controls & Sensors
        entities:
          - switch.smartplug_kitchen1
          - binary_sensor.hue_motion_sensor_kitchen_motion
          - sensor.hue_motion_sensor_kitchen_temperature
          - sensor.hue_motion_sensor_kitchen_illuminance
          
  - title: Bedroom
    path: bedroom
    icon: mdi:bed
    theme: modern-home
    cards:
      - type: entities
        title: Bedroom Lights
        entities:
          - light.bedroom1
          - light.bedroom2
          - light.bedroom3
          
      - type: horizontal-stack
        cards:
          - type: button
            entity: light.candle_lights
            name: Candle Mode
            icon: mdi:candle
            tap_action:
              action: toggle
          - type: button
            entity: script.all_lights_off
            name: All Off
            icon: mdi:lightbulb-off
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.all_lights_off
                
  - title: Kid Bedroom
    path: kid_bedroom
    icon: mdi:teddy-bear
    theme: modern-home
    cards:
      - type: entities
        title: Kid Bedroom Lights
        entities:
          - light.livingroom3
          
      - type: horizontal-stack
        cards:
          - type: button
            entity: light.livingroom3
            name: Kid Light
            icon: mdi:teddy-bear
            tap_action:
              action: toggle
          - type: button
            entity: script.all_lights_off
            name: All Off
            icon: mdi:lightbulb-off
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.all_lights_off
            
  - title: Hall & Spaces
    path: hall
    icon: mdi:home-outline
    theme: modern-home
    cards:
      - type: entities
        title: Hallway & Dressing Areas
        entities:
          - light.hall1
          - light.bathroom1
          
      - type: entities
        title: Motion Sensors
        entities:
          - binary_sensor.hue_motion_sensor_hallway_motion
          - sensor.hue_motion_sensor_hallway_temperature
          - sensor.hue_motion_sensor_hallway_illuminance
          
  - title: Utilities
    path: utilities
    icon: mdi:wrench
    theme: modern-home
    cards:
      - type: entities
        title: Security Camera
        entities:
          - camera.cam01
          
      - type: entities
        title: UPS Battery Backup
        entities:
          - sensor.ups_status
          - sensor.ups_battery_charge
          - sensor.ups_battery_runtime
          - sensor.ups_battery_voltage
          - sensor.ups_beeper_status
          - sensor.ups_input_voltage
          - sensor.ups_load
          
  - title: Scenes & Automation
    path: automation
    icon: mdi:play-circle
    theme: modern-home
    cards:
      - type: horizontal-stack
        cards:
          - type: button
            entity: light.candle_lights
            name: Candle Lights
            icon: mdi:candle
            tap_action:
              action: toggle
          - type: button
            entity: script.all_lights_off
            name: All Lights Off
            icon: mdi:lightbulb-off
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.all_lights_off
          - type: button
            entity: script.morning
            name: Morning Scene
            icon: mdi:weather-sunny
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.morning
                
      - type: entities
        title: Home Modes & Status
        entities:
          - input_boolean.vacation_mode
          - input_boolean.guest_mode
          - input_select.benjamin_status_dropdown
          
      - type: conditional
        conditions:
          - entity: input_boolean.vacation_mode
            state: "on"
        card:
          type: markdown
          content: |
            ## 🏖️ Vacation Mode Active
            - Security automations enabled
            - Lights simulating presence
            - Energy saving mode active