---
# HomeKit Integration Automations
# This automation enhances the HomeKit experience and provides better integration

- alias: "HomeKit Bridge Started"
  description: "Notify when HomeKit bridge is successfully started"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: homekit.bds_home_assistant
      state: "running"
  action:
    - delay: "00:00:30"  # Wait for bridge to fully initialize
    - service: notify.all_smartphones
      data:
        title: "HomeKit Ready 🏠"
        message: "HomeKit bridge is running and ready for iOS devices"
        data:
          color: green
