---
# HomeKit Integration Automations
# These automations enhance the HomeKit experience and provide better integration

- alias: "HomeKit Bridge Started"
  description: "Notify when HomeKit bridge is successfully started"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: homekit.bds_home_assistant
      state: "running"
  action:
    - delay: "00:00:30"  # Wait for bridge to fully initialize
    - service: notify.all_smartphones
      data:
        title: "HomeKit Ready 🏠"
        message: "HomeKit bridge is running and ready for iOS devices"
        data:
          color: green

- alias: "HomeKit Motion Triggered Lighting"
  description: "Smart lighting based on motion sensors for HomeKit users"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hue_motion_sensor_hallway_motion
        - binary_sensor.hue_motion_sensor_kitchen_motion
      to: "on"
  condition:
    - condition: numeric_state
      entity_id: sensor.hue_motion_sensor_hallway_illuminance
      below: 50  # Only trigger in low light conditions
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.hue_motion_sensor_hallway_motion
              state: "on"
          sequence:
            - service: light.turn_on
              entity_id: light.hall1
              data:
                brightness_pct: 75
                transition: 2
        - conditions:
            - condition: state
              entity_id: binary_sensor.hue_motion_sensor_kitchen_motion
              state: "on"
          sequence:
            - service: light.turn_on
              entity_id: light.lightstripkitchen1
              data:
                brightness_pct: 80
                transition: 2

- alias: "HomeKit Auto Lights Off"
  description: "Automatically turn off lights when no motion detected"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hue_motion_sensor_hallway_motion
        - binary_sensor.hue_motion_sensor_kitchen_motion
      to: "off"
      for: "00:10:00"  # 10 minutes after motion stops
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.hue_motion_sensor_hallway_motion
              state: "off"
              for: "00:10:00"
          sequence:
            - service: light.turn_off
              entity_id: light.hall1
              data:
                transition: 5
        - conditions:
            - condition: state
              entity_id: binary_sensor.hue_motion_sensor_kitchen_motion
              state: "off"
              for: "00:10:00"
          sequence:
            - service: light.turn_off
              entity_id: light.lightstripkitchen1
              data:
                transition: 5

- alias: "HomeKit Vacation Mode Activated"
  description: "Secure the home when vacation mode is enabled via HomeKit"
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: "on"
  action:
    - service: light.turn_off
      entity_id: all
    - service: switch.turn_off
      entity_id: switch.smartplug_kitchen1
    - service: media_player.turn_off
      entity_id: media_player.living_room
    - service: notify.all_smartphones
      data:
        title: "Vacation Mode Activated 🏖️"
        message: "All lights and devices turned off for vacation mode"
        data:
          color: blue

- alias: "HomeKit Vacation Mode Deactivated"
  description: "Welcome back when vacation mode is disabled via HomeKit"
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: "off"
  action:
    - service: notify.all_smartphones
      data:
        title: "Welcome Back! 🏠"
        message: "Vacation mode disabled. Home systems reactivated."
        data:
          color: green

- alias: "HomeKit Guest Mode Smart Adjustments"
  description: "Adjust automation behavior when guests are present"
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      to: "on"
  action:
    - service: notify.all_smartphones
      data:
        title: "Guest Mode Active 👥"
        message: "Home automation adjusted for guest comfort"
        data:
          color: orange