---
- alias: "Turn a few lights on when there is high cloud coverage"
  trigger:
    - platform: numeric_state
      entity_id: sensor.clichy_cloud_cover
      above: 60
    - platform: numeric_state
      entity_id: sensor.clichy_cloud_cover
      below: 100
  condition:
    condition: and
    conditions:
      - condition: time
        after: "17:00"
        before: "20:00"
      - condition: state
        entity_id: group.family
        state: "home"
      - condition: state
        entity_id: light.livingroom
        state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.sun_gets_dim

- alias: "Turn a few lights on when the sun gets dim"
  initial_state: "True"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 3.5
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.sun_gets_dim

- alias: "Turn more lights on as the sun gets dimmer"
  initial_state: "True"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 1.5
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.sun_gets_dimmer

- alias: "Turn on nightlight at dusk"
  initial_state: "True"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -5
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.nightlight

- alias: "Turn on lights when dark and we Just Arrived"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: sensor.benjamin_status
      to: "Just Arrived"
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
    - service: scene.turn_on
      entity_id: scene.just_arrived
    - service: switch.turn_on
      entity_id: switch.smartplug_kitchen1

- alias: "Turn on kitchen lights when there is a movement"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.hue_motion_sensor_kitchen_motion
    to: "on"
  condition:
    - condition: numeric_state
      entity_id: sensor.hue_motion_sensor_kitchen_illuminance
      below: 150
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.smartplug_kitchen1
    - service: light.turn_on
      data_template:
        entity_id:
          - light.kitchen_lights
        color_temp: >
          {%- if now().strftime('%H') | int >= 20 %}
            450
          {%- elif now().strftime('%H') | int >= 7 %}
            350
          {%- else %}
            500
          {%- endif %}
        brightness_pct: >
          {%- if now().strftime('%H') | int >= 20 %}
            60
          {%- elif now().strftime('%H') | int >= 8 %}
            80
          {%- else %}
            50
          {%- endif %}

- alias: "Turn off kitchen lights few minutes after last movement"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.hue_motion_sensor_kitchen_motion
    to: "off"
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: switch.turn_off
      entity_id: switch.smartplug_kitchen1
    - service: light.turn_off
      entity_id:
        - light.kitchen

- alias: "Turn on dressing lights when there is a movement"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.hue_motion_sensor_dressing1_motion
      - binary_sensor.hue_motion_sensor_dressing2_motion
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.dressing
        color_temp: >
          {%- if now().strftime('%H') | int >= 20 %}
            450
          {%- elif now().strftime('%H') | int >= 7 %}
            350
          {%- else %}
            500
          {%- endif %}
        brightness_pct: >
          {%- if now().strftime('%H') | int >= 20 %}
            60
          {%- elif now().strftime('%H') | int >= 8 %}
            80
          {%- else %}
            50
          {%- endif %}

- alias: "Turn off dressing lights few minutes after last movement"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.hue_motion_sensor_dressing1_motion
      - binary_sensor.hue_motion_sensor_dressing2_motion
    to: "off"
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: light.turn_off
      entity_id:
        - light.dressing

- alias: "Turn on living room lights when there is a movement and when dark"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.livingroom_motion_sensor
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: "home"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: state
        entity_id: light.livingroom1
        state: "off"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.livingroom1
        color_temp: >
          {%- if now().strftime('%H') | int <= 9 %}
            350
          {%- else %}
            500
          {%- endif %}
        brightness_pct: >
          {%- if now().strftime('%H') | int <= 9 %}
            30
          {%- else %}
            70
          {%- endif %}

- alias: "Turn off living room lights when there is not movement and when dark"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.livingroom_motion_sensor
    to: "off"
    for:
      minutes: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: "home"
      - condition: state
        entity_id: light.livingroom1
        state: "on"
      - condition: time
        after: "02:00:00"
        before: "06:00:00"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
  action:
    - service: light.turn_off
      entity_id:
        - light.livingroom1

- alias: "Turn off all lights when everybody is Away"
  initial_state: "True"
  trigger:
    platform: state
    entity_id: sensor.benjamin_status
    to: "Away"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: "not_home"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
  action:
    - service: light.turn_off
      entity_id: all
    - service: notify.all_smartphones
      data:
        message: All light turned off 💡
        data:
          color: green
