---
- alias: "Turn a few lights on when the sun gets dim"
  initial_state: "True"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 3.5
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: hue.activate_scene
      data:
        transition: 60
      target:
        entity_id:
          - scene.hallway_read
          - scene.livingroom_read

- alias: "Turn more lights on as the sun gets dimmer"
  initial_state: "True"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 1.5
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: hue.activate_scene
      data:
        transition: 60
      target:
        entity_id:
          - scene.hallway_read
          - scene.livingroom_read
          - scene.kitchen_read

- alias: "Turn on lights when dark and we Just Arrived"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: sensor.benjamin_status
      to: "Just Arrived"
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: light.livingroom
        state: "off"
  action:
    - service: hue.activate_scene
      target:
        entity_id:
          - scene.hallway_relax
          - scene.livingroom_read
          - scene.kitchen_read

- alias: "Turn off all lights when everybody is Away"
  initial_state: "True"
  trigger:
    platform: state
    entity_id: sensor.benjamin_status
    to: "Away"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: "not_home"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
  action:
    - service: light.turn_off
      entity_id: all
    - service: notify.all_smartphones
      data:
        message: All light turned off 💡
        data:
          color: green
