---
- alias: "Turn off Media Players when everybody is Away"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: sensor.benjamin_status
      to: "Away"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: "not_home"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
  action:
    - service: media_player.turn_off
      entity_id: media_player.apple_tv_livingroom
    - service: media_player.media_pause
      entity_id: media_player.living_room_2
    - service: notify.all_smartphones
      data:
        message: All media players was turned off 🔇
        data:
          color: green
