---
# Automating Transitions Between States
# https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/
- alias: "Mark person as just arrived"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: person.benjamin
      from: "not_home"
      to: "home"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'person.benjamin' %}
            input_select.benjamin_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'person.benjamin' %}
            {% if states.input_select.benjamin_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %}

- alias: "Mark person as home"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: input_select.benjamin_status_dropdown
      to: "Just Arrived"
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.benjamin_status_dropdown
      from: "Just Left"
      to: "Just Arrived"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.benjamin_status_dropdown' %}
            input_select.benjamin_status_dropdown
          {% endif %}
        option: Home

- alias: "Mark person as just left"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: person.benjamin
      from: "home"
      to: "not_home"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'person.benjamin' %}
            input_select.benjamin_status_dropdown
          {% endif %}
        option: Just Left

- alias: "Mark person as away"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: input_select.benjamin_status_dropdown
      to: "Just Left"
      for:
        minutes: 20
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.benjamin_status_dropdown' %}
            input_select.benjamin_status_dropdown
          {% endif %}
        option: Away

- alias: "Mark person as extended away"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: input_select.benjamin_status_dropdown
      to: "Away"
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.benjamin_status_dropdown' %}
            input_select.benjamin_status_dropdown
          {% endif %}
        option: Extended Away
