---
- alias: "UPS status changed"
  initial_state: "True"
  trigger:
    platform: state
    entity_id:
      - sensor.ups_status
  action:
    - service: notify.all_smartphones
      data:
        title: APC status summary 🔋
        message: |
          Status: {{ states("sensor.ups_status") }}
          Battery: {{ states("sensor.ups_battery_charge") }}
          Battery runtime: {{ states("sensor.ups_battery_runtime") }}
          Battery voltage: {{ states("sensor.ups_battery_voltage") }}
          Input voltage: {{ states("sensor.ups_input_voltage") }}
          Load: {{ states("sensor.ups_load") }}
        data:
          color: red

- alias: "Power outage finished"
  initial_state: "True"
  trigger:
    platform: state
    entity_id:
      - sensor.ups_status_data
    from: "OB DISCHRG"
    to: "OL CHRG"
  action:
    - service: notify.all_smartphones
      data:
        message: Power is back 🔋
        data:
          color: green
    # wait few minutes to let hue bridge reboot after a power outage
    # TODO: buy an APC with more battery backed slots
    - delay: "00:02:00"
    - service: notify.all_smartphones
      data:
        message: Turn all lights are off after the power outage 💡
        data:
          color: green
    - service: light.turn_off
      entity_id: all
