---

- alias: 'Simulate presence'
  trigger:
    - platform: state
      entity_id: 'sun.sun'
      to: 'below_horizon'
    - platform: event
      event_type: event_simulate_presence
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
      - condition: time
        before: '00:00:00'
      - condition: state
        entity_id: group.family
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    - service: script.turn_on
      data:
        entity_id: script.simulate_presence

- alias: 'Turn off presence simulation when family arrive home'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'home'
  condition:
    - condition: state
      entity_id: script.simulate_presence
      state: 'on'
  action:
    - service: script.turn_off
      data:
        entity_id: script.simulate_presence
