---
- alias: "Turn on vacation mode when away for 24h"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: group.family
      to: "not_home"
      for:
        hours: 24
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode
    - service: switch.turn_off
      entity_id: switch.hot_water_cylinder
    - service: notify.all_smartphones
      data:
        message: Vacation mode had been turned on automatically because everyone is away since 24h ⛱️
        data:
          color: green

- alias: "Turn off vacation mode when coming home"
  initial_state: "True"
  trigger:
    - platform: state
      entity_id: group.family
      to: "home"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacation_mode
    - service: switch.turn_on
      entity_id: switch.hot_water_cylinder
    - service: notify.all_smartphones
      data:
        message: Vacation mode had been turned off 🧳
        data:
          color: green
