---
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  #- job_name: node-exporter
  #  static_configs:
  #    - targets:
  #        - localhost:9100
  - job_name: snmp
    static_configs:
      - targets:
          - router.bds.home.arpa
    metrics_path: /snmp
    params:
      module:
        - pfsense
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: nas.bds.home.arpa:9116 # The SNMP exporter's real hostname:port.
