---
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node-exporter
    static_configs:
      - targets:
          - router.bds.home.arpa:9100
