---
global:
  body_size_limit: 16MB
  sample_limit: 5000
  label_limit: 64
  label_name_length_limit: 128
  label_value_length_limit: 512
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node-exporter
    static_configs:
      - targets:
          - router.bds.home.arpa:9100
