---
- platform: statistics
  entity_id: sensor.hue_motion_sensor_dressing2_temperature
  name: bedroom_temperature

- platform: statistics
  entity_id: sensor.hue_motion_sensor_hallway_temperature
  name: hallway_temperature

- platform: statistics
  entity_id: sensor.hue_motion_sensor_kitchen_temperature
  name: kitchen_temperature

- platform: statistics
  entity_id: sensor.hue_motion_sensor_kitchen_light_level
  name: kitchen_luminance

- platform: history_stats
  name: Time in bed
  entity_id: binary_sensor.in_bed
  state: "on"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 24
