---
- platform: google_wifi
  host: wifi.bds.home.arpa
  monitored_conditions:
    - current_version
    - new_version
    - uptime
    - last_restart
    - status

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: last_boot
