---
- platform: airvisual
  api_key: !secret airvisual_api_key
  monitored_conditions:
    - us
    - cn
  city: paris
  state: ile-de-france
  country: france
  show_on_map: false

- platform: darksky
  api_key: !secret darksky_api_key
  language: en
  monitored_conditions:
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - cloud_cover
    - daily_summary
    - dew_point
    - hourly_summary
    - humidity
    - minutely_summary
    - nearest_storm_distance
    - ozone
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_type
    - pressure
    - summary
    - temperature
    - temperature_high
    - temperature_low
    - uv_index
    - visibility
    - wind_bearing
    - wind_speed
