#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

COMPOSE_HTTP_TIMEOUT=300

export COMPOSE_HTTP_TIMEOUT

if [[ "$(whoami)" != 'admin' ]]; then
  echo "Script must be run as user 'admin'"
  exit 1
fi

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do
  sudo -n true
  sleep 60
  kill -0 "$$" || exit
done 2>/dev/null &

if [[ ! -d "${HOME}/Code/bds.home.arpa" ]]; then
  mkdir "${HOME}/Code"
  chmod 0755 "${HOME}/Code"
  git clone https://github.com/bdossantos/bds.home "${HOME}/Code/bds.home.arpa"
fi

pushd "${HOME}/Code/bds.home.arpa" >/dev/null
git checkout .
git pull
sudo docker-compose pull
sudo docker-compose up --remove-orphans -d
popd >/dev/null

if [[ ! -d "${HOME}/Code/dockerfiles" ]]; then
  mkdir "${HOME}/Code"
  chmod 0755 "${HOME}/Code"
  git clone https://github.com/bdossantos/dockerfiles "${HOME}/Code/dockerfiles"
fi

cp -f etc/prometheus/prometheus.yml /volume1/docker_datas/prometheus/prometheus.yml
sudo chown -R 65534:65534 /volume1/docker_datas/prometheus/

pushd "${HOME}/Code/dockerfiles" >/dev/null
git checkout .
git pull
popd >/dev/null
