#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

if [[ "$(whoami)" != 'admin' ]]; then
  echo "Script must be run as user 'admin'"
  exit 1
fi

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if [[ ! -d "${HOME}/Code/bds.home" ]]; then
  mkdir "${HOME}/Code"
  chmod 0755 "${HOME}/Code"
  git clone https://github.com/bdossantos/bds.home "${HOME}/Code/bds.home"
fi

pushd "${HOME}/Code/bds.home" >/dev/null
  git checkout .
  git pull
  sudo docker-compose build --pull
  sudo docker-compose up -d
popd >/dev/null
