#!/usr/bin/env python
"""
This scrip setup my Phillips hue Groups, etc.
"""

import re
from phue import Bridge

BRIDGE = Bridge('hue.bds.home')
BRIDGE.connect()

LIGHTS = BRIDGE.lights
GROUPS = [
    'bathroom',
    'bedroom',
    'dressing',
    'hall',
    'kitchen',
    'livingroom',
]

for group in GROUPS:
    if not BRIDGE.get_group(group):
        PATTERN = re.compile(group + '*')
        BRIDGE.create_group(
            group,
            [light.light_id for light in LIGHTS if PATTERN.match(light.name)]
        )

print BRIDGE.get_group()
