---
name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # ratchet:docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # ratchet:docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # ratchet:docker/login-action@v4
        with:
          username: bdossantos
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Dockefile build context, image name and tags
        shell: bash
        id: context
        run: |
          version=$(egrep ' VERSION=(.*)$' 'Dockerfile' | sed 's/^.*=//')
          vcs_ref=$(git rev-parse --short HEAD)
          image_name='home-assistant'
          tags=bdossantos/${image_name}:latest,bdossantos/${image_name}:${version},bdossantos/${image_name}:${version}-${vcs_ref}
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "path=$(dirname ${{ inputs.dockerfile }})" >> $GITHUB_OUTPUT
          echo "tags=${tags}" >> $GITHUB_OUTPUT
          echo "vcs_ref=${vcs_ref}" >> $GITHUB_OUTPUT
      - name: Build and push docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # ratchet:docker/build-push-action@v7
        with:
          build-args: |
            BUILD_DATE=${{ steps.context.outputs.build_date }}
            VCS_REF=${{ steps.context.outputs.vcs_ref }}
          context: ${{ steps.context.outputs.path }}
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.context.outputs.tags }}
